# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker
      run: docker build -t oauth-server:v1.0.0 .
    - name: Push docker
      run: |
       docker login --username=zyzbeckham@gmail.com --password=Flzx3qc! registry.cn-beijing.aliyuncs.com
       docker tag oauth-server:v1.0.0 registry.cn-beijing.aliyuncs.com/readheart/oauth-server:v1.0.0
       docker push registry.cn-beijing.aliyuncs.com/readheart/oauth-server:v1.0.0